node-fetch/node-fetch

lib/response.js
test/test.js

https://github.com/whatwg/fetch/commit/e62f57b6c923f16e877ab56913a2a65388a7535a

Add a convenience `ok` getter on `Response`

---

index.js

minor optimization / code golf

timeout tweak

---

CHANGELOG.md
index.js
test/server.js
test/test.js

New release

---

lib/request.js
lib/response.js
test/test.js

Added parsing of Headers in Response & Request constructors
Added support of string bodies in Response

Fix for #33

---

lib/headers.js
test/test.js

Add Headers.forEach method.

---

index.js
lib/body.js
lib/headers.js
lib/request.js
lib/response.js
test/test.js

Support string/buffer bodies in Response constructor
Request should have Body methods like text(), json()

Fix for #38 and #36

---

.travis.yml
CHANGELOG.md
index.js
lib/body.js
lib/headers.js
lib/request.js
lib/response.js
package.json
test/server.js
test/test.js

Prepare new release v1.4.0

---

index.js
lib/body.js
lib/error.js
lib/fetch-error.js
test/test.js

Following up on #7 
test.js's formatting looks bad unless the tab size is 2. Suggestions?

Error codes

---

CHANGELOG.md
LIMITS.md
README.md
index.js
lib/body.js
test/server.js
test/test.js

August bugfix

---

README.md

Got to many "how do i handle binary/images" issues

added 2 binary exemple

---

CHANGELOG.md
lib/body.js
package.json
test/server.js
test/test.js

+ some cosmetic whitespace fixes

Return empty .json() object on 204. Fix #165.

---

package.json
src/body.js
src/fetch-error.js
src/index.js
src/request.js
src/response.js
test/server.js
test/test.js

Elements of this commit come from #140 by @gwicke.

Convert all files to ES2015

---

CHANGELOG.md
UPGRADE-GUIDE.md
src/headers.js
src/index.js
test/test.js

Remove FOLLOW_SPEC option; make it the default behavior

---

README.md

docs(defaults): list of default header values

---

package.json
src/index.js

2.0.0 alpha 4

---

index.js

Just to keep all codes the same.

Add the missing comma

---

README.md
package.json
src/body.js
src/request.js
test/test.js

Accept URLSearchParams as body and detect for setting form-urlencoded header

---

src/body.js
test/test.js

Should fix #293.. sorry I didn't realize initially that issue thread was meant as a reminder *to yourself* lol. Feel free to reject but, figured I was already at the party :p

wrap JSON.parse's SynaxError with FetchError

---

package.json
test/test.js

Fix test cases

---

CHANGELOG.md
package.json

and start to take notes in changelog on what each alpha release fixes.

prepare next release (alpha.8)

---

src/index.js

Support TypeScript import

---

src/request.js
test/test.js

where lowercase method name does not trigger type error

fix a small oversight in request class 

---

package.json
src/body.js
test/test.js

adds support for ArrayBuffer body in requests. Part of #247

ArrayBuffer body

---

src/headers.js
src/index.js
src/request.js
test/test.js

Regression since 1592ca1148e657110fd6f64dc8b29a576cd1da1c.
Fixes: #416
Fixes: #425

Fix custom Host header with arbitrary case

---

src/index.js

Unfortunately, I could not write a test case that allows testing the bug
in #428.
Fixes: #428

Make sure to finalize the request properly

---

.travis.yml

Consolidate Travis CI matrix for encoding

---

src/body.js
test/test.js

Added support for `ArrayBufferView`

---

README.md
test/test.js

This is all that's left of #473, #474, and #475. Less code, less bugs. Yay!

document and test using a custom dns lookup function through agent

---

src/body.js
test/test.js

Also add more test coverage.
Fixes: #459
/cc @nazar-pc

Fix up ArrayBufferView support

---

browser.js

Support web workers

---

CHANGELOG.md
LIMITS.md
README.md
package.json
src/body.js
src/index.js
src/request.js
src/response.js
test/test.js

Plus some other doc related update.

Fix import style to workaround node < 10 and webpack issues.

---

src/body.js
src/request.js
src/response.js
test/test.js

...and set correct content-type in response constructor
followup on #520

Clone urlsearchparams to avoid mutation

---

src/index.js
test/server.js
test/test.js

pass custom timeout to subsequent requests

---

src/blob.js

Fix import for older node versions and webpack.

---

package.json
types/externals.d.ts
types/index.d.ts

Migrated the type definitions from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node-fetch.

feat: Migrated types

---

src/index.js
test/test.js

This PR adds support for Data URIs using native methods in Node 5.10.0+ (closes #311).

feat: Data URI support

---

src/headers.js
test/server.js
test/test.js

fix: Convert Content-Encoding to lowercase

---

package.json
src/index.js

Fixes #309 
This PR replaces all `stream.pipe()` with [`pump`](https://www.npmjs.com/package/pump).

Fix stream piping

---

src/errors/fetch-error.js
test/test.js

Include system error in FetchError if one occurs

---

.travis.yml
README.md
docs/v3-UPGRADE-GUIDE.md
index.d.ts
package.json
src/body.js
test/server.js
test/test.js

This PR replaces the `encoding` optional dependency with `fetch-charset-detection`.
Fixes #554.
cc @bitinn @xxczaki

refactor: Replace `encoding` with `fetch-charset-detection`.

---

package.json

More information here: https://blog.opencollective.com/beyond-post-install/

Add `funding` field to package.json

---

docs/CHANGELOG.md
src/request.js

Closes #704 
Signed-off-by: Richie Bendall <richiebendall@gmail.com>

feat: Allow excluding a user agent in a fetch request by setting it's header to null.

---

index.d.ts
src/response.js
test/test.js

feat: Added missing redirect function

---

src/index.js

Original PR by @kennethaasan: #699 
Created against the `3.x` branch.

fix: Use req.setTimeout for timeout

---

package.json
src/index.js

See: https://github.com/node-fetch/node-fetch/issues/668#issuecomment-612937339

Compile CJS modules as a seperate set of files

---

package.json
src/request.js
src/utils/get-search.js
test/main.js
test/utils/server.js

Original PR by @dzek69 (#777)
Fixes #776

fix question mark stripped from url when no params are given (#776) 

---

.github/workflows/ci.yml
.github/workflows/lint.yml
README.md
package.json

Fix GitHub Actions

---

.github/workflows/ci.yml
.github/workflows/lint.yml

See https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

Fix GitHub Action paths glob

---

.github/ISSUE_TEMPLATE/feature-request.md

another issue template 
related to #811

Add feature request issue template

---

.github/ISSUE_TEMPLATE/support-or-usage.md

issue template for support questions
related to #811

Add support issue template

---

.github/ISSUE_TEMPLATE/config.yml

Add issue configuration

---

.github/ISSUE_TEMPLATE/config.yml

Added blank issues creation, for those issues that don't fit the categories listed above in the issue creation page.
NaN
Nope.

Enable blank issue creation

---

README.md

Fix import statement.
Misleading import statement.

Fix Headers import statement

---

README.md

Fixes examples in Advanced Usage section of README.md to use correct variable `response` instead of `res`.
None
None

fix: update docs with correct variables

---

docs/CHANGELOG.md
package.json

- ~~fetch-blob@1.0.7 breaks tests~~ https://github.com/node-fetch/node-fetch/pull/870

Release 3.0.0-beta.7

---

docs/ERROR-HANDLING.md

fixed typo
To solve Fetch Error issue in my project,
I copied this example code and applied it to my code, and an error occurred.
I found a typo.
I want to contribute, so I ask for PR.
```js
const fetch = require('node-fetch'); <--
```
```js
const fetch = required('node-fetch');
(async () => {
try {
await fetch(url, {signal});
} catch (error) {
if (error.name === 'AbortError') {
console.log('request was aborted');
}
}
})();
```

fix: typo in docs/ERROR-HANDLING.md

---

docs/CHANGELOG.md
package.json
src/utils/is.js

Related to https://github.com/node-fetch/node-fetch/issues/908

Release 3.0.0-beta.8

---

CHANGELOG.md
src/index.js
test/test.js

Honor the `size` option after following a redirect and revert data uri support

---

src/index.js

No doc, bug or feature changes
No related issue
just a small optimization to avoid creating unnecessary anonymous functions

Minor optimization

---

docs/CHANGELOG.md

Fix changelog

---

docs/ERROR-HANDLING.md

Fix indent

---

test-new/body.js
test-new/fetch-error.js
test-new/headers.js
test-new/main.js
test-new/request.js
test-new/response.js

fixes: #832 
@xxczaki - I'm hoping you can help me with the 6 tests that are currently skipped. I'm unsure on how to test the timeout tests with Ava at moment. :)

chore: Ava

---

test/headers.js

Added test for `Header[Symbol.for('nodejs.util.inspect.custom')]`
none
no

Test custom inspect function for `Header`

---

README.md

fix formdata-node example

---

src/headers.js
src/request.js
test/headers.js

Added `thisArg` to Header's forEach method and `header` parameter on its callback.
#1072 
There's an unrelated lint issue on `src/request.js` that's breaking the CI checks.

Improve Header's forEach method compliance with browser implementation.

---

test/main.js
test/utils/server.js

Added a test case to verify that `statusText` results in an empty string when it doesn't exist in the response.
#1066 

Test empty statusText

---

README.md

Added a link above the table of contents in the readme to direct v2 users to the correct documentation.
Fixes #1184

Add link to v2 docs

---

README.md

Made 2 README.md changes:
- Fixes a dead link introduced by #1141
- Corrected spelling to "metadata"
No.

chore: Correct stuff in README.md

---

README.md

Closes #1396
Updates Readme such that the `@types/node-fetch` refs the last known version with valid types (`@types/node-fetch@2.x`); targets users who cannot upgrade to `node-fetch@3.x`
n/a
___
> __Note to reviewers of this PR:__
> because of the minuscule nature of this change I have not updated the Changelog – I feel such an addition would add a bit of unnecessary "noise" to the real additions to the codebase.
> also, ty for writing such an amazing lib <3

update readme for TS @types/node-fetch

---

.github/workflows/ci.yml

fixes GH actions builds from `main`
___
___
- Fixes #000

ci: fix main branch

---

README.md
src/utils/referrer.js
test/utils/server.js

code base consistency
___
___
- Fixes #000

fix: use more node: protocol imports

---

src/utils/is.js

Follow up to https://github.com/node-fetch/node-fetch/pull/1449#discussion_r784110707
Make the code easier to understand in `isDomainOrSubdomain`
https://github.com/node-fetch/node-fetch/pull/1449#discussion_r784110707

Simplify check in isDomainOrSubdomain

---

README.md

docs(readme): correct typo around import statment

---

package.json
src/body.js
test/main.js
test/request.js

Pull the plug on deprecated form-data package
___
___
- fix #1167

chore: completely remove support for form-data package

---

README.md

Update the changelog URL since the old changelog file was removed.
Just a one line change in README.md - update the link.
This is my first PR so please let me know if I've dome something wrong :) Cheers!
___
- [*] I updated readme

docs(readme): Replace changelog with valid url

---

@types/index.d.ts

FormData not exported in type def
___
___
- fix #1517

fix: add missing formdata export to types

---

README.md

fix a code example where it had a extra `)` in the code example.
___
- fix #1561

docs: fix file constructor code example

---

README.md

docs: spelling in readme

---

CHANGELOG.md

Update 2.x changelog to include missing releases
https://github.com/node-fetch/node-fetch/releases/tag/v2.6.7
https://github.com/node-fetch/node-fetch/releases/tag/v2.6.6
___
___

fix(changelog): update 2.x changelog

---

README.md

fix missing comma in import statement of [Example code](https://github.com/node-fetch/node-fetch#post-data-using-a-file)
___
___

docs: fix missing comma in example

---

README.md

Corrected readme with HTTPResponseError with correct constructor and usage
updated readme
___
___
- fix #001

(1138) - Fixed HTTPResponseError with correct constructor and usage
