node-fetch/node-fetch

lib/response.js

We're currently getting 
```[Error: Encoding not recognized: 'UTF-8; QS=1' (searched as: 'utf8qs1')]```
errors when using `node-fetch`, due to our `Content-Type` response header having the value 
```application/json; charset=UTF-8; qs=1```,
i.e. a value after the `charset`
This PR just makes the charset extraction less greedy, so stop on a semi-colon

Less greedy charset matching

---

index.js
test/test.js

Otherwise node.js waits it. In other words, if you make a request with, say, 10 seconds timeout, your script will run for about 10 seconds doing nothing.

Clear request timeout after response

---

README.md
index.js
test/test.js

addresses https://github.com/bitinn/node-fetch/issues/17

expose response and headers constructors

---

index.js
test/server.js
test/test.js

Some of the requests we make from the server need to overwrite the host header (e.g. for ‘apis’ which were originally written with a CDN in mind and we're just making requests that act like a CDN) and node-fetch currently chokes if you try to set a custom host header, check out e98f22b3ba8350a37c6f3c8917df56655e5c4fc7, run `npm test` and you'll get this output:-
```
1) node-fetch should allow setting of custom host:
TypeError: undefined is not a function
at Agent.createSocket (_http_agent.js:186:39)
at Agent.addRequest (_http_agent.js:166:23)
at new ClientRequest (_http_client.js:154:16)
at exports.request (http.js:49:10)
at /Users/mandrews/sandboxes/node-fetch/index.js:83:13
at new Fetch (/Users/mandrews/sandboxes/node-fetch/index.js:44:9)
at Fetch …
```

Allow a custom host to be set

---

README.md
index.js
package.json
test/test.js

This is convenient for isomorphic apps that rely on form-data.

Automatically pull headers from node-form-data.

---

index.js

Old source do not add content-length header automatically
with form-data. If body is instance of form-data, Users
must missing this header. It cause parse error with some
server engine like WSGI. WSGI must drop body if this was not
set, and WSGI based frameworks such as flask can not read
form data.
For example, this python code with flask..
```py
from flask import Flask, request, jsonify
app = Flask(__name__)
@app.route('/', method=['POST'])
def index():
return jsonify(**request.form)
app.run()
```
Can not receive any data from this code.
```js
require('es6-promise').polyfill();
var fetch = require('isomorphic-fetch'); // it use node-fetch
var FormData = require('form-data');
var data = new FormData();
data.append('name', 'item4');
data.append('message', 'it is test!'); …
```

Add content-length header with form-data

---

index.js

This adds a default export so it could be used
with es6 modules default export as well without
breaking api.

Align with es6 modules

---

lib/body.js
test/test.js

closes #91 
Note that we can't really properly clone a FormData object without having it as a dependency of node-fetch, so I choose to just pass the reference ahead. Hopefully no one is going to clone Request instance with FormData object and somehow expect it to be a complete new clone.

Fix formdata support when you are trying to wrap the request

---

lib/request.js

Check `init.agent` and `input.agent` just once and default to `undefined`.

request.js: remove unneeded input.agent

---

lib/response.js

As documented in the fetch spec https://fetch.spec.whatwg.org/#dom-response, the status should default to 200
```
dictionary ResponseInit {
unsigned short status = 200;
ByteString statusText = "OK";
HeadersInit headers;
};
```
While the aim of node-fetch isn't to 100% match the spec, this seems like a reasonable bit of compliance to add.
Note - this PR implicitly sets status text to 'OK' too

default to 200 response status

---

.travis.yml
CHANGELOG.md
ERROR-HANDLING.md
README.md
index.js
package.json

Unfortunately this lowers our coverage a bit because npm doesn't allow me to install 2 different versions of `form-data` (I have to test it using environment variables).
If we drop `form-data` 1.x support it will be a breaking change (thus bumping `node-fetch` to 2.x) but I want to keep it as 1.x until we can safely drop both Node 0.10 and 0.12 support (still accounts for 20% of production environment per [April 2016 survey](https://nodejs.org/static/documents/2016-survey-report.pdf)).
TL;DR: support both `form-data` 1.x and 2.x for now in `node-fetch` 1.x, and by the end of this year, we will bump to `node-fetch` 2.x and drop `form-data` 1.x support in there.

Testing both form-data 1.x and 2.x support

---

README.md

Wasn't sure initially if `JSON.stringify()` for post body would work, then it took me longer than it should have to work out that `Content-Type` was needed for POST JSON to work with koa-body (and perhaps other body parsers?), so this might help others.

Add 'post javascript object' example to readme

---

src/headers.js
src/index.js
src/request.js
src/response.js
test/test.js

Closes #127, #174.
The approach taken by this pull request versus #174 is that the iterator methods are greatly simplified as well as more correct w.r.t. the behavior of `keys()` in case of multiple values.

Convert Headers to ES2015 and implement Iterable interface

---

package.json
src/body.js
src/request.js
src/response.js
test/test.js

* Simplify `Request` and `Body` classes
* Add support for `body.arrayBuffer()` (using [buffer-to-arraybuffer](https://www.npmjs.com/package/buffer-to-arraybuffer) to gain support on older Node.js compared to #140)
* Fix spec compliance when body is `null`
* Add more tests

Miscellaneous improvements over #182

---

src/common.js
src/headers.js
src/index.js
test/test.js

Fixes #181. I did add a `FOLLOW_SPEC` option, and made the test suite run twice -- once with `FOLLOW_SPEC` enabled and once disabled. To use it one would do:
```js
const fetch = require('node-fetch');
fetch.FOLLOW_SPEC = true;
```

Improve Headers compatibility

---

src/body.js
test/test.js

Also uses iconv-lite directly instead of using the "encoding" package.
Fixes #184.

Add a new res.textConverted() and always use UTF-8 for res.text()

---

package.json
src/request.js
test/test.js

Fixes #175. As a side effect, after this PR `new Request(null)` will not throw anymore, and therefore more conforming to the spec.

Support WHATWG URL objects

---

src/body.js
test/test.js

This reverts commit 95b58936b8673f7fdc21050c3bfeb460e9b00bf1.
Fixes #165.

Revert "Return empty .json() object on 204. Fix #165. (#166)"

---

src/body.js
src/index.js
src/request.js

Currently the Request objects used in a fetching process is hijacked to become the second parameter to [`http.request`](https://nodejs.org/api/http.html#http_http_request_options_callback) method, and code from distinct areas of the specification are interspersed in the giant `fetch()` function. This not only means that auditing with the spec in mind is difficult, the Request object contains multiple properties that are not technically in the specification (e.g. `protocol`, `path`, etc.), making isomorphic usage confusing.
This PR separates the Request object and the Node.js `http.request` options object, providing an internal function to convert the former to the latter. Also split are Content-Type and Content-Length extraction functions, which in the specification is grouped into the …

Refactor request options

---

src/blob.js
src/body.js
test/test.js

The `Blob` class isn't currently exposed as it is not really interoperable with any other library (the buffer is opaque from the user), and so far the only use cases for it in Node.js are for isomorphism with the browser. Eventually I might write a full implementation for the W3C File API in Node.js, so until then I don't want to encourage the use of it.
Fixes #78.

Add support for blobs

---

.babelrc
build/babel-plugin.js
build/rollup-plugin.js
package.json
rollup.config.js
src/index.js
test/test.js

The following description is now irrelevant and incorrect.
----
This should be the last functional change before a 2.0.0-alpha.1 release. It makes it possible to use this module directly with [Rollup](http://rollupjs.org/), which we are already using to generate the output bundles.
The main concern can be that it requires more typing on the user's part. However, it is not always true:
Before:
```js
import fetch from 'node-fetch';
import fetch, { Headers, Response } from 'node-fetch';
const fetch = require('node-fetch');
const fetch = require('node-fetch');
const fetch = require('node-fetch');
const { Headers, Response } = fetch;
const fetch = require('node-fetch');
const Headers = fetch.Headers;
const Response = fetch.Response;
```
After:
```js
import { fetch } from 'node-fetch';
import { …
```

Use ES2015 export syntax

---

.babelrc
.travis.yml
package.json
src/headers.js

Your docs says that `2.x` dropping support for `node 0.x` while Babel transpilling still targets that version. This PR fixes that as well as dropping `0.x` from travis, updates `babel-preset-env` to latest version and adding appropriate `engines` to `package.json`

transpilling to Node 4 instead of dropped 0.x

---

package.json
src/body.js

Same method of `Stream` detection is used at `koa` sources, so, I believe it's pretty bulletproof.
And since `node 4.x` is minimum supported version now, we can also drop `buffer-to-arraybuffer` and use `slice` directly for converting to `ArrayBuffer`

remove is-stream and buffer-to-arraybuffer in favor of native methods

---

src/headers.js
src/response.js
test/test.js

Without this change the headers get flattened in [`/src/headers.js#L42-L70`](https://github.com/bitinn/node-fetch/blob/a1e76b97e18f28395bdb46e3a849800f52ee8027/src/headers.js#L42-L70). This is a result of an iterator [`/src/headers.js#L197-L199`](https://github.com/bitinn/node-fetch/blob/a1e76b97e18f28395bdb46e3a849800f52ee8027/src/headers.js#L197-L199) using getter [`/src/headers.js#L89-L96`](https://github.com/bitinn/node-fetch/blob/a1e76b97e18f28395bdb46e3a849800f52ee8027/src/headers.js#L89-L96) that joins multiple header values into a comma separated list.

fix: do not re-initialize Headers (fixes #251)

---

src/headers.js
test/test.js

See spec for combined values: https://fetch.spec.whatwg.org/#concept-header-value-combined
I don't know if a different spec clause overrides the need for that space.

headers.get: add space to join

---

README.md
src/index.js
src/request.js
test/test.js

This reverts commit ec29e3d2640586bc07cddf894e2aa10461b20ec0.
This patch prevents any agent being passed in which is not explicitly an instance of `http.Agent`. This makes `node-fetch` no longer compatible with https://npm.im/proxy-agent, which is one example of a library that does not directly inherit from `http.Agent` directly.
Sorry for the revert -- I don't have an alternative patch because I don't believe this is something node-fetch should be doing automatically, because of how much of a limitation this could impose.
The original PR stated that this was to prevent requiring http/https, and the effect would effectively be to force creation of an Agent on every call. Note that this is already the behavior specified for 
http.Agent when http.request received `false`. (See the bottom of …

Revert "Allow passing agent option as an object (#236)"

---

ERROR-HANDLING.md

Sidenote. I feel this sentence:
> All errors originating from Node.js core are marked with `err.type = 'system'`, and in addition contain an `err.code` and an `err.errno` for error handling. These are aliases for error codes thrown by Node.js core.
Could be a little more clear on the distinction between `code` and `errno`, or at least link to the relevant Node documentation. I'd add it myself but I'm not clear on the distinction myself 😅 .
Thanks for a great lib!

Small improvements to the error-handling wording

---

README.md

Just noticed this was left out while looking through a response instance. Outside of whether I think this property is useful or not I think we can agree it's good to document our public properties 😄.
Thanks for a great lib!

Document response.ok convenience property

---

browser.js
package.json

This makes `node-fetch` reference the browser native fetch API when bundled for the browser.
https://github.com/bitinn/node-fetch/issues/262

use browser natives when bundled for the browser

---

.gitignore
test/server.js

Node 8 http server now supports Keep-Alive connection pooling, one of the tests use keep-alive agent which causes `server.close()` to timeout mocha.
I will submit a PR for 2.x branch when available...

1.x branch: fix test server for node 8 release

---

src/blob.js
src/body.js
test/test.js

Just need a sanity check:
blob.js line 34... Buffer.from(ArrayBuffer) or Buffer.from(ArrayBuffer#buffer) ?

refactor deprecated `new Buffer` with Buffer.from and Buffer.alloc

---

package.json

explicitly exclude node 5 from engines directive

---

lib/headers.js

On [jest](https://www.npmjs.com/package/jest) test framework, cannot receive http header array.
Test project
https://github.com/H1Gdev/test_set_cookie
1. npm install
2. npm test
**Expect**
-> receive 'set-cookie' header.
**Actual**
-> cannot receive 'set-cookie' header.

Fix cannot receive http header array issue.

---

lib/fetch-error.js
test/test.js

The `.stack` property gets cached in the `captureStackTrace()` call, so
whatever is set as the `name` and `message` at that time will be used
for the first line of the stack trace.
Before this patch, FetchError's stack would just say "Error" as the
first line. Now they correctly display the "${name}: ${message}" of the
error instances.
Test case included.
Signed-off-by: Timothy Gu <timothygu99@gmail.com>

proper stack first line for FetchError instances (#215)

---

package.json

`browser.js` isn't in the npm package, so it doesn't work in browsers. This should fix it.

add browser.js to npm published files

---

README.md

I am making some changes to Readme:
- Adding comment to recommend 2.x releases;
- Adding an alternative to `isomorphic-fetch`;
One thing I am considering:
- Now that MDN is basically the official doc for every major browsers, should we just link to it instead of listing all spec compliant interfaces/classes in Readme? We probably only need to document the differences.
- Since we are not going to take 2.x out of alpha due to Fetch Spec itself is constantly evolving; shall we at some point switch to 2.x alpha as our latest (mainline) npm release?

Adding comment to recommend 2.x branch

---

src/body.js
test/test.js

Add error event hander for the body stream even if the body isn't accessed

---

src/index.js
src/request.js
test/server.js
test/test.js

When the server returns a 307 redirect, `node-fetch` does not post the request body to the new URL, but `fetch` does, at least in Chrome.
Here is a failing test from https://github.com/octokit/rest.js/pull/764
https://travis-ci.org/octokit/rest.js/jobs/348045840#L4095
The same test passes when run in Chrome
https://travis-ci.org/octokit/rest.js/jobs/348045843#L4040
I tried to create a test case to reproduce the problem, does that look good? I’m not sure how to fix it though, I’d appreciate pointers :)

307 redirect with PATCH & body

---

src/body.js
src/index.js
src/response.js
test/test.js

Most of the code base already consistently uses the tab + comma-at-the-end style. This converts the rest.

Harmonize style

---

src/body.js
test/test.js

Initializing `Request` and `Response` with array buffers causes issues for `.text()`:
```javascript
const { Response } = require('node-fetch');
const response = new Response(new Uint8Array[97]);
response.text().then(text => {
// text === '[object ArrayBuffer]', should be 'a'
});
```
The problem is due to the fact that `ArrayBuffer.toString()` returns `[object ArrayBuffer]` instead of decoding the `ArrayBuffer`. Converting the `ArrayBuffer` to a `Buffer` fixes `.text()` and `.json()`.

wrapped ArrayBuffer with buffer internally to fix body methods

---

src/body.js
test/test.js

I'm not totally sure whether we should reject this as a `FetchError`, so please let me know, if not (and I'll update the PR accordingly). The underlying error here should always be a `RangeError`.
As for testing: unfortunately, there doesn't appear to be any great way to test this (the `RangeError` is thrown when the buffer size is larger than the maximum allowed by v8 itself, which isn't configurable from within the tests). The best I could do here was to temporarily overwrite `Buffer.concat`, which is used by node-fetch internally, to force it to throw an error, and then insure that the error is passed on via a `Promise` rejection.

Reject when stream accumulation fails (Fix #414)

---

browser.js

Related to #307 and #332.
TypeScript is compiling
```
import fetch from 'node-fetch';
fetch(url, options)
```
into
```
const node_fetch_1 = require("node-fetch");
node_fetch_1.default(url, options)
```
This works great in Node.js thanks to #332 but doesn't work in the browser (I'm using Webpack, so it correctly uses the `browser.js` script specified in `package.json`).

Support TypeScript import in browser

---

browser.js

Fixes `fetch` illegal invocation errors in Chrome. This is the same as https://github.com/developit/unfetch/pull/47
As mentioned [here](https://github.com/bitinn/node-fetch/pull/433#issuecomment-375917867), there's an issue in some browsers and Webpack with fetch not being bound to `window` in Webpack.

Bind fetch to window in the browser

---

README.md

This reverts commit fa6548ed316a3c512147a3bb4f4d6e986d738be6 (#441).
The autoClose option has been true by default since at least Node.js
v6.0.0. There is no need to set it once more.
Instead, make the example more realistic by handling stream outcomes
using a promise.
See #375.

Refine README example

---

ERROR-HANDLING.md
README.md
package.json
src/abort-error.js
src/body.js
src/index.js
src/request.js
test/server.js
test/test.js

Whether or not you actually deprecate timeout should probably be a separate issue (#523) - but I think at the very least there should be support for `AbortSignal` here.
Let me know if you would need any changes to make this happen!

Add support for AbortSignal to cancel requests

---

CHANGELOG.md
browser.js

By trying to guess available global.
- And no, we are not going to fix cases where `global`, `self` or `window` isn't actually global.
- And no, we are not going to check `this` is global, I know v8/jsc shell might need it, but it was not our goal to make `node-fetch` *just work* there.
People, you have to deal with your own mistakes here.
ref: https://github.com/tc39/proposal-global

Workaround lack of self in react-native

---

src/body.js

Forgot to make a PR. 
Hade it ready two days ago
This remove some redundant code by normalizing the input body to buffer and eventually make it easier to make a stream getter out of it (`res.body`, `req.body`)
Report:
```
----------------|----------|----------|----------|----------|-------------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------|----------|----------|----------|----------|-------------------|
All files       |    96.07 |    92.93 |      100 |    95.98 |                   |
abort-error.js |      100 |      100 |      100 |      100 |                   |
body.js        |    88.39 |    80.16 |      100 |       88 |... 16,320,321,326 |
fetch-error.js |      100 |      100 |      100 |      100 |                   | …
```

Unify body to buffer

---

src/headers.js
test/test.js

Related: https://github.com/github/fetch/pull/684 , https://github.com/denoland/deno/pull/1427
From https://tools.ietf.org/html/rfc7230#section-3.2,
```
header-field   = field-name ":" OWS field-value OWS
field-name     = token
```
and
```
token = 1*tchar
```
In Chrome, appending a header with empty field name throws and error:

Headers should not accept empty field name

---

src/blob.js
test/test.js

- added missing `;`
- added missing blob.toString()
- added missing blob.stream() - this returns a node stream.
closes #604

support reading blob with stream

---

.gitignore
src/index.js
test/server.js
test/test.js

[Native support](https://github.com/nodejs/node/pull/24938)
[Node Documentation](https://nodejs.org/api/zlib.html#zlib_class_zlib_brotlidecompress)

Adding Brotli Support

---

package.json
test/test.js

While doing an `npm install`, I saw that the `url-search-params` package is deprecated, and needed to be replaced.  See https://www.npmjs.com/package/url-search-params for more details!

chore(deps): address deprecated url-search-params package

---

package.json

Enabling `--throw-deprecation` for the tests ensures that no deprecated methods are being used in nodejs.  I'm trying to track down a node.js 12 property deprecation, and figured I may as well do this while I was in here :)

test: enable --throw-deprecation for tests

---

.npmrc

With `package-lock.json` ignored, it's better to just tell `npm` not to generate it at all.  This removes the need for developers on the package to keep deleting `package-lock.json` and re-installing to get the latest patch versions of transitive deps.

build: disable generation of package-lock since it is not used

---

src/body.js

Allow third party blob implementation

---

CHANGELOG.md
README.md
package.json
src/index.js
src/response.js
test/test.js

besides doc update, also includes an implementation of `redirected` property

2.5.0 release

---

src/body.js
src/request.js
src/utils/is.js

fix: Better object checks

---

browser.js

We ran into some issues where this was executed in browsers that didn't support fetch (e.g. IE11)

check for global.fetch before binding it

---

README.md
src/body.js
src/index.js
src/request.js
src/response.js
test/chai-timeout.js
test/server.js
test/test.js

Fixes #386 
This PR uses some bits from #563, but instead of passing the custom highWaterMark to `clone` method, it is passed via node-fetch options:
```diff
- fetch(url).then(res => res.clone(10).buffer());
+ fetch(url, {highWaterMark: 10}).then(res => res.clone().buffer());
```
I used the same tests from #563 to confirm that everything works as expected. However, it would be great if someone could review my changes to check whether I made any mistakes :smile:

Allow setting custom highWaterMark via node-fetch options (#386)

---

src/body.js
test/server.js
test/test.js

`convertBody`function work fine when html has this meta tag.
`<meta http-equiv="content-type" content="text/html;charset=shift_jis">`
However, if the `http-equiv` attribute is reversed like this, it will not work.
`<meta content="text/html; charset=Shift_JIS" http-equiv="Content-Type" />`

fix: Properly parse meta tag when parameters are reversed

---

src/index.js

The original error message does not provide enough information about what went wrong. It simply states a configuration setting.

Change error message thrown with redirect mode set to error

---

docs/v3-UPGRADE-GUIDE.md
src/body.js
test/test.js

fix: Throw SyntaxError instead of FetchError in case of invalid JSON

---

package.json
src/index.js

Turns out, our implementation of data URI to buffer conversion was quite flawed. It always assumed base64 encoding (which wasn't the case when it came to the failing test) and tried to retrieve the non-existent `Buffer.body` property.
I was going to refactor the logic but I realised [`data-uri-to-buffer`](https://www.npmjs.com/package/data-uri-to-buffer) already did **exactly** what we wanted.
\
\
oh and the build is passing WOOO 🎉
cc @bitinn @xxczaki

fix: Proper data uri to buffer conversion

---

src/body.js

This patch fixes a problem where not all prototype methods are copied from the Body via the mixin method due to a failure to properly detect properties in the target. The current code uses the in operator, which may return properties lower down the inheritance chain, thus causing them to fail the copy. The new code properly calls the .hasOwnProperty() method to make the determination

Flawed property existence test

---

src/request.js

As requested within #707, PR for v3 branch.
The underlying "right" thing may be for users of FormData to not have to rely on NaN, but for FormData to support streams of unknowable length out of the box, but it can't hurt for node-fetch to check for NaN in the meantime.
See further discussion (hopefully!) at form-data/form-data#394.

Fix: Do not set ContentLength to NaN

---

docs/ERROR-HANDLING.md

This PR fixes a small regression in error handling documentation introduced by #745

Fix the path to tests file in error handling doc

---

README.md

Filetype dependency changes. If not changed, the example can cause an TypeError for `const fileType`.

Fix example using `file-type`

---

src/body.js
src/index.js
test/main.js
test/utils/delay.js

There is a single timeout option which applies to both the receiving of
response headers and the receiving of the entire response body. Once
the response is received, the socket timeout must be cleared to allow
the timeout to apply to the receiving of the entire response body.
Without clearing the socket timeout, if the nearing the idle timeout
when the Promise for the body is created, then the request's timeout
handler will abort the request, emitting ERR_STREAM_PREMATURE_CLOSE in
the body Promise.
By clearing the socket timeout once the response headers are received,
the timeout for the entire body can be started when the body is awaited.
Since the request will no longer be aborted by the socket timeout,
destroy is called on the body to prevent it continuing to emit data
events. …

fix: Disambiguate timeout behavior for response headers and body

---

README.md
docs/CHANGELOG.md
docs/v3-UPGRADE-GUIDE.md
package.json
src/index.js
src/request.js

Brotli is supported in Node.JS core since version 10.16 and it was handled in `node-fetch` under the guard on receiving, however it wasn't set on request. This PR fixes and documents that support.

Add Brotli support in Request

---

src/index.js
src/response.js
src/utils/is-redirect.js

- Fixes `isRedirect` hackish "export" as property on default export to be a real ES6 named export
- Replace array creation and iteration on each call with static O(1) Set
- Reuse `isRedirect` at `Response` class

Move `isRedirect` function to a seperate file

---

src/body.js
src/utils/is.js

Replaces custom implementation of `isArrayBuffer` in favor of `util.types.isAnyArrayBuffer` available since Node 10.0

Use built-in method for `isArrayBuffer`

---

src/request.js

`Stream.Readable.destroy` is available since Node 8.x, so, guard is no more needed as our minimum requirement now is 10.16

Remove guard for Stream.Readable.destroy

---

src/body.js
test/main.js
test/utils/server.js

👋 Hi, the newly added test demonstrates that the `consumeBody` promise would never settle if the body stream was closed prematurely by the server.
---------
The stream.finished function is used consolidate the terminal cases.
The writable option must be set to false, since the body stream is
a Duplex stream, but our terminal cases only apply to the Readable side.

Settle `consumeBody` promise when the response closes prematurely

---

src/index.js

Normalizes `export` syntax in index.js

Normalize `export` syntax

---

src/body.js
src/request.js
src/response.js

I'm sure there is a reason behind the original decision to use `Body.mixIn` instead of normal class inheritance, but this reason is not reflected in current tests (as they all are passing after this refactoring).
On the other hand, using normal class inheritance, first of all, makes code easier to understand, and also works way better with static code analyzing based tooling, like IntelliSense in Visual Studio Code. It also will help if the team will decide to switch to a TypeScript one day, etc.
By the end, it's just the standard language construction for this use case.
It also will be required step to my approach to have this project typings automatically generated by TypeScript out of JSDoc, that's currently impossible due to `Body.mixIn` …

Use normal class inheritance instead of Body.mixIn

---

.github/workflows/commonjs.yml
package.json
test/commonjs/package.json
test/commonjs/test-artifact.js

These changes add a script that builds and tests the fitness of CommonJS build artifact at `prepublishOnly` command.
Should prevent incidents like #836 
Comes with GitHub Action watchdog for build-related files

Test CommonJS build artifact

---

README.md
package.json
src/body.js
src/index.js
test/main.js
test/utils/server.js

Fixes #844 and drops custom Promises.
This PR didn't complete the refactoring of `index.js` into `async` function (as it way more complicated and time-consuming task), but it can be done by iterations later on as non-breaking changes, now when we drop support for custom promises.
No changes to tests, except for the removal of testing for custom promises.

Drop custom Promises and refactor to `async` functions

---

@types/index.d.ts
@types/index.test-d.ts
package.json
src/headers.js

- Export all types and interfaces
- Use `class` instead of `interface`+`var` where it's possible
- Use a minimal type for `AbortSignal` to avoid the need to import 'abort-controller' module
- Use method declaration instead of lambda declaration
- Avoid namespace creation that is not needed
- Impossible to construct `RequestInit` or `ResponseInit` object correctly:
```typescript
const init: RequestInit = { /* ... */ };
```
- Impossible to build a TypeScript project with no `abort-controller` dependency
- Not compatible with `v3.0.0-beta.5` types
- check if `isRedirect()` is useable in …

fix: improve TypeScript types

---

package.json
src/index.js
src/request.js
test/external-encoding.js
test/main.js

This PR adds a breaking test for existing dataUri implementation and reimplements it without using RegExp and also drops them in Request, following browsers logic on this case.
Only changes to tests are breaking case (from Wikipedia) for current implementation and adjusting of error messages as they are coming from native URL parser now (unsupported protocol message is copied from Chrome `fetch`)

Fix Data URI handling and drop all URL analysis RegExps

---

README.md
src/request.js

Added option to pass `insecureHTTPParser` parameter to the http(s).request here https://nodejs.org/docs/latest-v12.x/api/http.html#http_http_request_options_callback.
It looks like there was recently a similar discussion around this for TLS Options, which can be configured on the agent (undocumented). The impetus for this PR is the ability to pass the `insecureHTTPParser` option, which as far as I can tell can't be set on the agent.
https://github.com/node-fetch/node-fetch/issues/724
See the previous discussion over here: https://github.com/node-fetch/node-fetch/pull/855
Here's some …

Add insecureHTTPParser Parameter

---

.github/workflows/ci.yml
src/headers.js

This PR makes use of native [header/value validation functions](https://nodejs.org/api/http.html#http_http_validateheadername_name) added in Node 14.3 and adjusts error message/code for our functions polyfilling the same behavior.

Polyfill `http.validateHeaderName` and `http.validateHeaderValue`

---

package.json
src/body.js
src/index.js
test/main.js
test/request.js
test/response.js

While working on #210 I went into a particular interpretation of fetch redirect step 9.
[fetch standard](https://fetch.spec.whatwg.org/#http-redirect-fetch):
```
If actualResponse’s status is not 303, request’s body is non-null, and request’s body’s source is null, then return a network error.
```
However, our source instead of body _source_ is checking created `Request.body`. This PR fixes that fact.
This is also important due to fact that we may (_want_) convert the body to a stream internally, so, we actually must check body source here.
In addition, well-outdated test dependency `resumer@0.0.0` was replaced with native `Readable.from`.
In addition, while doing the above replacement, the _hacky_ test for `Buffer.concat` failure was replaced …

[Spec] Should check body _source_ on redirect

---

src/body.js
src/errors/abort-error.js
src/errors/base.js
src/errors/fetch-error.js
src/index.js
src/utils/is.js
test/main.js

In the current implementation `AbortError` and `FetchError` pretty much repeating the same code (plus some magic strings). This PR moves common functionality into a base class and removes code duplication.
It also removes `isAbortError` and uses `instanceof FetchBaseError` as those errors are our internal classes and always instantiating from it.

chore: remove code duplication in custom errors

---

.editorconfig
package.json

I was wrong with my understanding of what _backported_ means in Node.js versions and `Readable.from` seems to skip the whole range of Node 11 (reached end of life already) and 3 earlier versions of Node 12.
This PR fixes that and removes the unneeded exemption from `eslint-plugin-node` rules.
~Not sure why diff become crazy here 😕~
Unrelated change to prevent such diffs in the future: added `package.json` into our `editorconfig`.

fix: min semver Node version

---

README.md
package.json

Even on browser-side Fetch API is also available in the Service Worker context, so, we should either write `WindowOrWorkerGlobalScope.fetch()` as in [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) or just `Fetch API` as this PR proposes.
I also added some keywords to `package.json` as most alternative projects are doing.

fix window.fetch

---

README.md

it is no longer supported in v3
Compare 
https://github.com/node-fetch/node-fetch/blob/1fdc218a64f8bc2c85bec0ca59a85973ef5e1f0a/%40types/index.d.ts#L56-L88

docs(README): remove node-only `timeout` option

---

package.json
test/main.js
test/request.js
test/response.js

This PR removes external test dependency `string-to-arraybuffer` in favor of Node.js built-in `util.TextEncoder` available since Node 8.30

chore: remove `string-to-arraybuffer` test dependency

---

test/headers.js
test/main.js
test/request.js
test/response.js
test/utils/server.js

This PR fixes our test suite to allow it to run in parallel with new mocha 8 feature:
`npx mocha --parallel`
It doesn't switch to this mode by default due to the fact that at the moment nor `c8` nor `nyc` can collect test coverage in this mode.
Basically this PR makes the test server to bind to a random port (0) instead of fixed one and removes the use of mocha _root hooks_.
One test was refactored into an async function because for some reason it was failing in parallel mode otherwise.
There are no speed improvements right now from running tests in parallel, mostly due to the fact that our current test suite is the monolith of one file, but it will/may improve both with mocha improvements and out tests de-composition, so, it's nice to have:
```sh
mocha --reporter=dot 
212 passing (2s) …
```

Allow Mocha tests to be run in parallel

---

package.json

Looks like a bad merge, `parted` was replaced by `busboy` at #603 and not in use in this project anymore.

chore: remove `parted` test dependency

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/support-or-usage.md

The default `title` value in our issue template is causing too much default title issues.
We want to make issue submission easy but not that easy, leaving them blank should force issue submitter to type something more useful.
Plus we had automate label assignment already, the heading is mostly superfluous. 
Issue templates
Issue titles
Please review and merge, hope I didn't break anything :)

Remove automatic title assignment from issue templates

---

src/request.js
test/main.js

This allows a falsey `signal` to be ignored.  e.g. 
```
fetch('https://google.com', { signal: undefined })
```
Fixes #1029
no

Allow `signal` to be `null` or `undefined`

---

src/request.js
src/utils/is.js
test/main.js

Node has added its own AbortController in 15.0.0. The AbortController signal
inherits from EventTarget. This changes the check to also accept signals of
type EventTarget.
https://nodejs.org/docs/latest-v15.x/api/globals.html#globals_class_abortsignal
Modified the `isAbortSignal` check to accept `EventTarget` as well.
Incompatibility with the new node `AbortController`

Support instances of `EventTarget` as a `signal`

---

src/index.js
test/main.js
test/utils/server.js

This "fixes" the issue of a missing return after reject (#890) by removing the try/catch and reject altogether.  A bad [Location header is escaped by the URL module](https://github.com/tekwiz/node-fetch/blob/398332cde15a9ef3104f02bc77a49a47d695df7e/src/index.js#L108), so any "corrupted" headers become valid or otherwise cause errors earlier in processing.  The bottom-line is that this call to reject can never happen.
Fixes #890
no

Fix missing return after reject

---

src/index.js
test/main.js

If an invalid `redirect` option is passed and a redirect does occur, the default case now throws a `TypeError`.
none
First, I consider this a backwards-incompatible change since the current code would simply ignore a redirection altogether with an invalid `redirect` value.  If back-porting is being considered for any changes, I recommend this **not** be considered for back-porting to v2.
Justification:
1. The Fetch specification defines [RequestRedirect](https://fetch.spec.whatwg.org/#requestredirect) as an enum; therefore, other values should not be allowed.
2. It seems more …

Throw a `TypeError` on an invalid redirect option

---

README.md

Using a variable named "json" for the parsed JSON data is confusing, because at that point the data is __not__ JSON anymore.
- [ X] Documentation update
I changed the variable named "json" in all the examples to "data". The result of calling `response.json()` is __not__ JSON anymore.
Clarified usage of the node-fetch API

Removing confusingly named 'json' variable in examples

---

README.md
src/index.js
test/main.js
test/utils/server.js

re. 47b00e179dd8a450f3fffd9ac22d148197a09229: For responses using chunked `Transfer-Encoding` without a `Content-Length`, this adds a check at the socket's `close` event to verify that the last bytes received were the final chunk bytes, i.e. `0\r\n`.  If not, it creates a `Premature close` error and sends it to `response.body.destroy()`.  Certain network errors evidently bypass the HTTP parser's error handling resulting in silent failures.  @davidje13 confirmed fix in #739 https://github.com/node-fetch/node-fetch/issues/739#issuecomment-754173198.
re. 13cdcf3d2fa514b76d60b5e73b5a8602e7d336b7: Before Node.js 14, pipeline() does not fully support async iterators and does not always properly …

Fix premature close with chunked transfer encoding and for async iterators in Node 12

---

package.json
test/main.js

1. Setup all AbortController tests to run for both abortcontroller-polyfill and abort-controller implementations to correctly catch and diagnose errors like what happened when abortcontroller-polyfill was bumped to 1.6 and 1.7.0 (see https://github.com/mo/abortcontroller-polyfill/issues/53).  
2. Bumped abortcontroller-polyfill dependency to 1.7.1 since 1.6 and 1.7.0 are breaking
none

Fully test both AbortController implementations, Bump abortcontroller-polyfill to 1.7.1

---

@types/index.d.ts

`insecureHTTPParser` was missing from the typings. This pull request adds it in.
Added `insecureHTTPParser` to the `RequestInit` interface.
#953.
No.

fix: Add missing insecureHTTPParser in RequestInit interface

---

@types/index.d.ts
README.md
src/response.js
test/response.js

Add support for `Response.error()` and `type`:
- https://developer.mozilla.org/en-US/docs/Web/API/Response/error
- https://developer.mozilla.org/en-US/docs/Web/API/Response/type

Add support for Response.error()

---

src/headers.js

Changed the `this` arg passed to the URLSearchParams prototype call in the Headers proxy handlers for `append()`, `set()`, `delete()`, `has()`, `getAll()`. Currently it's set to `receiver`, but it should be `target`, as it is [with the `keys()` handler](https://github.com/node-fetch/node-fetch/blob/d8fc32d6b29bd43d1ad377e80b3e439fe37f2904/src/headers.js#L137).
#917 
Ran the tests in Node (v14.15.0) and everything continues to pass. Manually tested in Electron (v11.1.1, with Node v12.18.3 and Chrome v87.0.4280.88), and it fixes the issue described in #917.

Fix `this` arg for URLSearchParams prototype call

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/types.yml
@types/index.test-d.ts
package.json
test/main.js

When switching to ESM in #1141 we are introducing three new minimum Node.js versions that we support:
- `12.20.0`
- `14.13.1`
- `16.0.0`
In order to not accidentally break any of those versions I propose that we test on them all.
This was previously sort of done with the `minimum-node-version` but it only supports a single version, so would thus only run on `12.20.0`.
n/a
n/a
-----
ping @jimmywarting: I didn't push this directly to the `esm` branch since this might something we want to discuss first?

Test on all minimum supported Node.js versions

---

src/index.js
test/main.js
test/utils/server.js

When an abort signal is given, the test for a properly closed chunked request should be skipped.
- fix #1220
- fix #1064 
- fix #1237

Fix(premature close) Redirect failing when response is chunked but empty

---

README.md
docs/CHANGELOG.md
docs/v3-UPGRADE-GUIDE.md

Few ppl started complaining about beta-10 going ESM and are unable to load it. The purpose of this PR is to provide them a alternative method to load ESM modules from CJS 
Have only updated some documents and suggested this way of loading fetch:
```js
// mod.cjs
const fetch = (...args) => import('node-fetch').then(mod => mod.default(...args));
```
There are both pro & cons with ESM. 
Bundle all dependencies and having own instances is not desirable. It can make working with different whatwg:streams versions incompatible
- [Dual Package Hazard](https://github.com/GeoffreyBooth/dual-package-hazard)
- [Node Modules at War: Why CommonJS and ES Modules Can’t Get Along](https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1)
- …

docs: Add example for loading ESM from CommonJS

---

docs/CHANGELOG.md
package.json

Going out of beta and marking v3 as stable
package.json version + changelog only
Have kind of forgot what the procedure is to release something on github/npm 
is there some auto release to npm when a github tag is generated or something?
___
___
- Fixes #668

V3 stable release

---

src/body.js

- We do serialize spec compatible FormData ourself now. 
- We like to reduce the complexity of the core by removing support for form-data. 
- form-data have had a long time to become spec compliant but haven't done that
- using `res.buffer` is no good as it's a nodejs only feature, if ppl depend on this it only makes it more node-specific
we now strive to more spec compatible ways and more cross platform solutions. 
This will output a one time warning when using form-data
___
___
- Fixes #1167

fix(Body): Discurage form-data and buffer()

---

docs/v3-LIMITS.md
src/index.js
src/request.js
test/main.js
test/request.js
test/utils/server.js

The previous `url.parse` did remove brackets from hostname the `new URL` don't do it.
To fix this i Replaced `https.request(options[, callback])` with `https.request(url[, options][, callback])` and letting NodeJS take care of parsing the the url
- This strips square brackets ([]) off hostnames that have them
- <s>implicit allow basic auth `http://username:password@hostname` that wasn't working before</s>
Closes #1267

fix: Pass url string to http.request

---

README.md

When i try to copy and paste the example code from https://github.com/node-fetch/node-fetch#streams, i got error and turns out the image link for https://assets-cdn.github.com/images/modules/logos_page/Octocat.png is dead. This PR just replace the image with new one, same as buffer example.

Fix octocat image link

---

CHANGELOG.md
package.json
rollup.config.js
src/request.js
test/server.js
test/test.js

- Documentation update
- New feature
- Other, please explain:
I've added a call to `encodeURI` before parsing a passed in string as an url
#1290 
This is basically a backport of #701, but keeps the old code path for arbitrary URLs on the `Request` object which was supported in 2.x

fix: properly encode url with unicode characters

---

CHANGELOG.md
package.json
src/request.js
test/test.js

fix v2.6.3 that did not send query params

---

CHANGELOG.md
package.json
src/request.js

- Documentation update
- New feature
- Other, please explain:
I imported `whatwg-url` in a way that is compatible with Node.js running in ESM mode.
https://github.com/node-fetch/node-fetch/commit/ace7536c955556be742d9910566738630cc3c2a6#r56836783
n/a
closes #1305

fix: import whatwg-url in a way compatible with ESM Node

---

README.md

Mention the Host header in the default request headers table.
According to the standard [RFC 7230 Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing](https://httpwg.org/specs/rfc7230.html#header.host)
> "A client MUST send a Host header field in all HTTP/1.1 request messages."
Add information to the documentation.

docs(Headers): Add default Host request header to README.md file

---

package.json
src/request.js
test/test.js

Use the newest URL instance whenever it's available.
- fix #1342 (but only for node v6.13.0 and above)

fix(URL): prefer built in URL version when available and fallback to whatwg

---

@types/index.d.ts
@types/index.test-d.ts

**What changes did you make?**
In https://github.com/node-fetch/node-fetch/pull/1078, the static `Response.redirect(url, status)` was added to the project but without typings which can be confusing for users. This pull request provides the typings for the method.

Add typing for Response.redirect(url, status)

---

README.md

- Add steps when using CommonJS
- Improve the polyfill example
Helps #1317

docs: Improve clarity of "Loading and configuring"

---

package.json

I installed node-fetch 2.x on my project with Yarn 2 (aka Yarn berry). When I call `require('node-fetch')`, I get this warning message:
```
(node:22404) [MODULE_NOT_FOUND] Error: node-fetch tried to access encoding, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```
It seems that `encoding` package is optional and only used in `body.textConverted()` method (discussed in #412).
So I added the following to `package.json` of node-fetch:
```json
"peerDependencies": { 
"encoding": "*"
},
"peerDependenciesMeta": {
"encoding": {
"optional": true
}
}
```
**Is there anything you'd like reviewers to …

2.x: Specify encoding as an optional peer dependency in package.json

---

.github/PULL_REQUEST_TEMPLATE.md

- To create a more task oriented list to help ppl remember to update the docs/changelog
- Creating more meaning full standardized title  
The tasks that shows up in the list of PR shows tasks.
It's often 1-2 out of 4 all the time. or 50% completed
I think we do not use them the "correct way" so I changed it. 
I also think this made the template less bloated, ppl don't like to read or follow the template so often 
( Less to read/follow === more they will write a better PR and actually follow the template/structure )
This PR uses this new template and this is what it looks like. (kind of... some parts are hidden/removed)
-------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------- …

template: Make PR template more task oriented 

---

README.md

Updating the readme examples
`body.buffer()` became deprecated and `Body.formData()` became supported
- So I removed the buffer examples and all ref to it
- And I removed the "not yet implemented in node-fetch" section about not supporting FormData in the body mixin
While at the same time i took the opportunity to change the suggested `AbortController` to be the built in first and formost. And how to upload a file using a `Blob`, that way the file size (content-length) will be added on the request
___

docs: Update code examples

---

docs/CHANGELOG.md
package.json

make a new release
Updated the minor version
When creating a release/tag in github then they had a "auto generate" feature, just took it and copied it straight to the changelog file
Any thoughts on using that instead and remove the changelog file that is buried in the docs folder?

release minor change (3.1.0)

---

README.md

header in TOC was broken and the path to esm was wrong
___
___
- Fix #1379

docs: Fix typo around sending a file

---

src/index.js
src/request.js

In #1268 we started to just forward the URL to node's Request method instead of sending everything as an option, This broke something as we where not passing it as a string.
I casted the URL into a string before handing the url to NodeJS http.request method
`send(parsedURL.toString(), options);`
___
- Fix #1376

fix(http.request): Cast URL to string before sending it to NodeJS core

---

docs/CHANGELOG.md
src/body.js
src/index.js
test/main.js

`node-fetch` does not handle errors from the request body stream correctly. This PR fixes it.
[`body.pipe(dest)`](https://github.com/node-fetch/node-fetch/blob/0284826de6e733c717447c6dfcddc5f0b538b254/src/body.js#L390) has been replaced with the `pipeline` function from the `stream` module.
___

fix: handle errors from the request body stream

---

docs/CHANGELOG.md
src/index.js
test/main.js
test/utils/server.js

Fixes crash when a Location header point to an invalid URL
Just wrapping `new URL()` in a try/catch and returning a sensible (?) error message
Test included
___
___
- Fixes #1386

fix(Redirect): Better handle wrong redirect header in a response

---

src/body.js

It was logging a warning for using deprecated `body.buffer()` implicit when calling `body.blob()`
construct blob using a arrayBuffer instead
___
- Fix #1401

core: Don't use buffer to make a blob

---

src/request.js
test/request.js

There was a regression introduced in a conditional which checks for a `body` override in `Request`, where brackets were at the wrong place. Because of this, in certain cases, one could create a GET/HEAD `Request` instance with a non-empty body, which should normally result in an `TypeError` thrown.
This PR fixes the issue, and adds a test for this particular case.
___
___

fix(Request): Fix logical operator priority to disallow GET/HEAD with non-empty body

---

package.json
src/body.js
src/index.js
test/external-encoding.js
test/headers.js
test/main.js
test/referrer.js
test/request.js
test/response.js
test/utils/read-stream.js

Attempt to deal with one of `xo`'s  new lint rule that global Buffer shouldn't be used
and prevents us from merging the new breaking version
- Some tests where changed to use TextEncoder instad of `Buffer.from`
- A base64 test was replaced to use `res.arrayBuffer()` instead of the deprecated  `res.buffer()`
- Two test where we test that Buffer is allowed as a body was removed... A buffer is just a instances of a Uint8Array and should be covered by this
- Other files that still use `Buffer` now imports it
xo that fails: https://github.com/node-fetch/node-fetch/runs/4349372595?check_suite_focus=true
___
___
- fix part of xo new breaking release

core: Don't use global buffer

---

src/index.js
src/utils/is.js
test/main.js
test/utils/server.js

Avoid forwarding secure headers such as authorization, www-authenticate, cookie & cookie2 when redirecting to a untrusted site. (so it follows browses origin policy) 
(matches Go [behavior](https://github.com/golang/go/blob/24239120bfbff9ebee8e8c344d9d3a8ce460b686/src/net/http/client.go#L1014))
When the location headers redirects to an other hostname, strip away secure request headers meant for the original destination
Should patch v2 also (not many can update to esm)
___
___
- Fixes #1443

fix(Headers): don't forward secure headers to 3th party

---

README.md
src/headers.js
src/index.js
test/main.js
test/utils/server.js

This removes the code that changes the location header to an absolute URL in the case of a manual redirect request. While doing this is helpful in most cases, it is too destructive in cases where the original, actual location header is needed.  See the situation described in #1086.
This change also [documents the variation from the spec](https://github.com/node-fetch/node-fetch/commit/8232b423f2d9df549e7a23cd6b6ebff23c8d744b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
This change reduces the total lines of code, thus reducing the overall test percentage for test coverage.  To keep that check passing, I added some appropriate c8 ignores to unrelated code (see …

Don't change relative location header on manual redirect

---

package.json
src/index.js
test/server.js
test/test.js

backport of #1449 as a bug/security fix

backport of #1449

---

docs/CHANGELOG.md
package.json

make a new release
see [changelog](https://github.com/node-fetch/node-fetch/blob/93345ea612da08d11215c3362a19e61c5eec03fb/docs/CHANGELOG.md)
___

3.1.1 release

---

src/index.js
test/server.js
test/test.js

**What changes did you make?**
This fixes an issue where older ISS servers (Definitely 7.5, but I can’t rule out other versions), could respond with a zero-length OK deflate response, hanging node-fetch. This was caused by the body stream never emitting a `data` event. A typical problematic response looks something like this:
```http
HTTP/1.1 200 OK
Content-Encoding: deflate
Content-Length: 0
Server: Microsoft-IIS/7.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
```
Our codebase uses node-fetch 2.6.0, but this is still an issue in v3. I’m not sure how to go about patching both branches.

Handle zero-length OK deflate responses

---

src/index.js
test/main.js
test/utils/server.js

**What changes did you make?**
This fixes an issue where older ISS servers (Definitely 7.5, but I can’t rule out other versions), could respond with a zero-length OK deflate response, hanging node-fetch. This was caused by the body stream never emitting a `data` event. A typical problematic response looks something like this:
```http
HTTP/1.1 200 OK
Content-Encoding: deflate
Content-Length: 0
Server: Microsoft-IIS/7.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
```
This is the master counterpart to the 2.x PR #903
I had to tweak it a bit compared to the 2.x version because `pump` would incorrectly reject on empty responses. 
- fix #1442
- fix #922
- fix #903

Handle zero-length OK deflate responses (master)

---

package.json
test/utils/server.js

dependabot wasn't able to update busboy cuz it had breaking changes...
Only affect the test server...
I was thinking maybe we don't really need the busboy...? we could just simply echo everything back and utilize node-fetch new `body.formData()` parsers.
and then do something like:
```js
fetch('/multipart', { method: 'post', body: formData })
.then(res => res.formData())
.then(formData => {
// expect responded formData to match the posted formData
})
```
Dos removing the dependency on busboy... 
___
___
- closes #1437

test: Update major busboy version

---

package.json
test/main.js

to tidy up and get rid of some indentation hell 
No other test file than main.js file was changed.
the test are still the same...

test: Modernize and convert some test in `main.js` to async/await

---

package.json
src/index.js
test/form-data.js
test/main.js
test/response.js

Making it easier to import and use `FormData, Blob & File`. Installing same dependency as `node-fetch` or otherwise getting them in a round-about way was hacky.
This re-export the stuff so it is available to use
___
___
- fix #1454

feat: export Blob, File and FormData + utilities

---

.github/workflows/ci.yml
README.md
docs/v4-LIMITS.md
docs/v4-UPGRADE-GUIDE.md
package.json

Have created a beta branch and tough to start working on it already
- update ci workflow to only test v14.17 and above
- created a v4 limits + upgrade doc
The documentation in v4 upgrade is changes to expect to come, they are not yet fixed...
___
___
- part of #1452

fix: drop support for Node 12

---

@types/index.test-d.ts
src/body.js
test/main.js
test/request.js
test/response.js

time to remove deprecated node-fetch only method `.buffer()`
___

chore: completely remove `.buffer()`

---

src/utils/is.js
test/main.js

should not check if a AbortSignal is of type EventTarget
___
___
- fix #1469

chore: remove EventTarget from the isAbortSignal

---

src/request.js

Was reading the code and found this typo. Easy fix
credentails -> credentials

chore: fix typo in credential error message

---

@types/index.d.ts
@types/index.test-d.ts

The `agent` option is (after being potentially called as as function)
passed directly to `http.request`. This is allowed to be
a boolean; `http.request` interprets `agent: false` as
"allocate a one-off Agent for this request", which is
distinct from `agent: undefined` which means to use a
default shared agent.
This PR updates the TS types to match the existing behavior.

fix: TS types support `agent: false`

---

README.md

Fixes cancel request example import.

fix: cancel request example import

---

src/body.js
test/response.js

long over due problem to an easy fix... `.text()` & `.json()` didn't handle BOM correctly
switch `buffer.toString()` to `TextDecoder().decode()`
___
___
- fix #541

fix: handle bom in text and json

---

CONTRIBUTING.md

To fix the broken Code of Conduct link in the README.md for the repo.
Just one commit that fixes the link.
I don't think there is an issue related to this.

docs: Code of Conduct link in Readme.

---

src/request.js
test/request.js

The purpose is to follow [Fetch Spec](https://fetch.spec.whatwg.org/#concept-method-normalize) 
As per spec:
To normalize a method, if it is a byte-case-insensitive match for `DELETE`, `GET`, `HEAD`, `OPTIONS`, `POST`, or `PUT`, byte-uppercase it. 
___
___
- fix #1538

fix: don't uppercase unknown methods

---

src/index.js

Since 8eeeec1 it seems listeners have been leaking on keep-alive sockets.
Apparently abort() has been deprecated since v17, using close() the onSocketClose listener is properly removed, and by creating a new onData function I'm able to remove the 'data' listener too.
___
___
- fix #1295

fix: Prevent unsubscribe from leaking listeners (#1295)

---

README.md

Reduce confusion
Update readme to remove an awaited `response.clone()` call in the `highWaterMark` section.
source code shows response is a sync call to a new Response constructor: https://github.com/node-fetch/node-fetch/blob/3944f24770b442e519eaff758adffc9ca0092bdb/src/response.js#L84-L101
___
___

docs(readme): remove `async` infront of `response.clone()`

---

src/index.js

Fixes a bug where `response.body` doesn't exist during some portion of the request lifespan (likely when aborted manually)
Check if both `response` and `response.body` exist before trying to destroy.
___

fix: undefined reference to response.body when aborted

---

src/request.js

Avoid warn `Request.data`, even if it is not used 
___
___
- fix #1549

fix: always warn Request.data

---

test/main.js

By relying upon a 100ms delay before aborting, it is possible for the request to succeed before being canceled.
Since these 2 tests merely ensures that cancellation via AbortController works, adding a delay isn't needed regardless.
Removes delay between request and canceling.
Undici runs node-fetch's test suite (more or less) and this test is flaky (https://github.com/nodejs/undici/runs/5153562802?check_suite_focus=true for example).
Example code with the issue fixed:
```js
import fetch from 'node-fetch';
import { createServer } from 'http';
import { once } from 'events';
const server = createServer((req, res) => res.end());
server.listen(3000, () => console.log('done'));
await once(server, 'listening');
let i = 1;
while (i++) {
try {
const controller = new AbortController();
const …
```

test: fix flaky tests

---

@types/index.d.ts

Remove the `dom` reference triple-slash directive from the typings file which pollutes the global ambient declarations with DOM types.
- fix #1285

chore: remove triple-slash directives from typings (#1285)

---

.babelrc
.travis.yml
README.md
package.json
rollup.config.js
src/index.js
test/server.js
test/test.js

This PR backports the fix from #1064 to the `2.x.x` branch following the [comment here](https://github.com/node-fetch/node-fetch/pull/1064#issuecomment-849167400).
I had to add some extra babel config to allow using the `for await..of` syntax in the tests.  The config is only needed for the tests as this syntax is not used in the implementation.

fix: premature close with chunked transfer encoding and for async iterators in Node 12

---

src/index.js
src/utils/is.js
test/main.js

Resolves https://www.huntr.dev/bounties/db31e05b-ff10-4057-81a3-37445bf161cd/ by validating that the URL protocol remains the same when determining whether to send secure headers on a redirect.
This prevents MITM attacks from sniffing secure headers when a redirect downgrades a `https://` to a `http://`
Adds an additional check to the redirect `follow` step to determine whether to send secure headers or not.
___
___

fix(Headers): don't forward secure headers on protocol change

---

src/utils/referrer.js

Fix Inefficient Regular Expression Complexity (ReDoS) in the referrer regex.
> Inefficient regular expression complexity regex when trying to match Potentially Trustworthy could lead to a denial of service attack. With a formed payload 'http://' + 'a.a.'.repeat(i) + 'a', 76 characters payload could take 42642 ms time execution. 
- Change `Potentially Trustworthy` regex matcher.
- [Report on Huntr](https://huntr.dev/bounties/a7e6a136-0a4b-46c4-ad20-802f1dd60bf7/)
___
___
- fix [#1609](https://github.com/node-fetch/node-fetch/issues/1609)

fix: ReDoS referrer

---

browser.js

Because of JS hoisting `var global` to the top of the file, `typeof global` in `getGlobal()` will always be `undefined`.
This can be a problem when bundling this code and running it in an environment that doesn't have `self` of `window` defined but has `global`.
In practice I ran into this issue after browserifying node-fetch and running the bundle in `node --experimental-fetch` (just to test).
I can confirm after this fix I can browserify node-fetch and have it expose the global `fetch` function when run into `node --experimental-fetch`.
By using a different variable name like `globalObject`, we are able to read the "real" `typeof global` and get access to the global object that way.

fix: prevent hoisting of the undefined `global` variable in `browser.js`

---

@types/index.d.ts
@types/index.test-d.ts
src/response.js
test/main.js

Implements static `Response.json` from https://github.com/whatwg/fetch/pull/1392
Adds static Response.json
___
___
- Fixes #1669

feat: add static Response.json

---

@types/index.d.ts
@types/index.test-d.ts

Fixes https://github.com/node-fetch/node-fetch/issues/1261
Added `URL` to `fetch` and `Request` constructor
Inspired by: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a9f480c82b3b356990e5dd574bf2c1ba9c2fdfb5/types/node-fetch/index.d.ts#L213 and https://github.com/microsoft/TypeScript/blob/f43cd0accac3e5033820fd27035731ed88f54938/lib/lib.dom.d.ts#L18281
___
___
- fix #1261

Allow URL class object as an argument for fetch()

---

src/index.js

Fix for this error.
TypeError: Cannot read properties of null (reading 'body')
Check if body exist
___
___
- fix #1700
- fix #1701

Prevent error when response is null

---

browser.js

I think this was missed in https://github.com/node-fetch/node-fetch/pull/1534
Replace `global` -> `globalObject`
I get a `global is not defined` error otherwise. (octokit is still using this instead of isomorphic-fetch/cross-fetch)

Fix "global is not defined"

---

README.md

Fix old example in the README.md file.
require -> import
according to different part of the same document
> node-fetch from v3 is an ESM-only module - you are not able to import it with require()

docs: readme - non ESM example

---

@types/index.d.ts

Dummy change with `fix:` commit to trigger the release of https://github.com/node-fetch/node-fetch/pull/1696
Swapped `RequestInfo | URL` around to `URL | RequestInfo` 🤷‍♂️
CI fail is irrelevant, same as [before](https://github.com/node-fetch/node-fetch/pull/1696/checks)

fix: release "Allow URL class object as an argument for fetch()" #1696

---

package.json
src/body.js
test/test.js

Reverts node-fetch/node-fetch#1739
it was breaking older NodeJS versions

fix: revert handle bom in text and json

---

src/index.js

Avoid issue where socket event was not triggered and local socket variable is not defined. This issue is reproducible only using deno.
#1725
Adds undefined testing to socket variable, protecting it from TypeError.
___
- fix #1725

fix: socket variable testing for undefined

---

README.md
src/request.js

This fixes #1735 and likely replaces #1473.
Removes the behaviour to add a `Connection: close` header. This was causing issues in Node.js 19+ (see #1735), but possibly subtle issues in earlier Node.js too. Note that we still expect some users to use `node-fetch` in Node.js 19+ because enabling fetch requires an `--experimental-fetch` command line parameter passed to Node.js and some users (such as people consuming my library which requires a `fetch` implementation) require it.
Instead, we rely on the underlying http implementation in Node.js to handle this, as per the documentation at
https://nodejs.org/api/http.html#new-agentoptions
The [original change introducing this](https://github.com/node-fetch/node-fetch/commit/af21ae6c1c964cd40e48e974af56ea2e1361304f) provided no clear motivation …

fix: Remove the default connection close header.

---

src/index.js

Backport of https://github.com/node-fetch/node-fetch/commit/553bb5dc5600b103905e3d40c722ebb387510a63 to v2.
Exports the AbortError, which is used internally and thrown on a timeout. https://github.com/node-fetch/node-fetch/blob/2.x/src/index.js#L81
https://github.com/node-fetch/node-fetch/issues/792
___
___
- fix #792

feat: `AbortError`
